# Tomcat
server:
  port: 8080
  servlet:
    context-path: /

# Spring
spring:
  application:
    # 应用名称
    name: ruoyi-gateway
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    inetutils:
      preferred-networks: @cloud.networks@
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: ${spring.profiles.active}
        namespace: @nacos.discovery.namespace@
      config:
        # 配置组
        group: ${spring.profiles.active}
        namespace: @nacos.config.namespace@
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml
