# Tomcat
server:
  port: 9203

# Spring
spring:
  application:
    # 应用名称
    name: ruoyi-job
  profiles:
    # 环境配置
    active: @profiles.active@

--- # dubbo IP 配置
dubbo:
  protocol:
    host: @cloud.inetutils.ip@

--- # nacos 配置
spring:
  cloud:
    inetutils:
      preferred-networks: @cloud.networks@
    sentinel:
      transport:
        client-ip: @cloud.inetutils.ip@
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: ${spring.profiles.active}
        namespace: @nacos.discovery.namespace@
        ip: @cloud.inetutils.ip@
      config:
        # 配置组
        group: ${spring.profiles.active}
        namespace: @nacos.config.namespace@
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml
