#FROM findepi/graalvm:java17-native
#FROM bellsoft/liberica-openjdk-debian:17
FROM bellsoft/liberica-openjdk-alpine:17
#FROM openjdk:17-jdk

# 作者
MAINTAINER chanbeiyu

# 外部传递参数
ARG VERSION
ARG SERVICE_NAME
ARG SERVICE_PORT
ENV VERSION=$VERSION
ENV SERVICE_NAME=$SERVICE_NAME
ENV SERVICE_PORT=$SERVICE_PORT

# 系统编码
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
# 运行参数
ENV JAVA_OPTS=""
ENV SW_AGENT_SERVICE_NAME=""
ENV SW_COLLECTOR_BACKEND_SERVICE=""

# 声明一个挂载点，容器内此路径会对应宿主机的某个文件夹
VOLUME /tmp

# 应用构建成功后的jar文件被复制到镜像内，名字也改成了app.jar
ADD ./build/${SERVICE_NAME}-${VERSION}.jar /home/app/app.jar
COPY ./agent/skywalking-agent.jar /home/agent/agent.jar

# 声明运行时端口
EXPOSE ${SERVICE_PORT}

# 启动容器时的进程
ENTRYPOINT ["java", \
            "-javaagent:/home/agent/agent.jar=agent.service_name=${SW_AGENT_SERVICE_NAME},collector.backend_service=${SW_COLLECTOR_BACKEND_SERVICE}", \
            # "-Dskywalking.agent.service_name=${SW_AGENT_SERVICE_NAME}", \
            # "-javaagent:/agent/agent.jar", \
            "${JAVA_OPTS}", \
            "-Djava.security.egd=file:/dev/./urandom", \
            "-jar", "/home/app/app.jar"]
