version: '3.8'

services:
  sky-oap:
    image: apache/skywalking-oap-server:9.3.0
    container_name: sky-oap
    hostname: sky-oap
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      JAVA_OPTS: -Xms1G -Xmx2G
      #记录数据的有效期，单位天
      SW_CORE_RECORD_DATA_TTL: 7
      #分析指标数据的有效期，单位天
      SW_CORE_METRICS_DATA_TTL: 7
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: 127.0.0.1:9200
      LANG: ${LANG}
      TZ: ${TZ}

  sky-ui:
    image: apache/skywalking-ui:9.3.0
    container_name: sky-ui
    hostname: sky-ui
    ports:
      - "18080:18080"
    environment:
      SW_SERVER_PORT: 18080
      SW_OAP_ADDRESS: http://127.0.0.1:12800
      LANG: ${LANG}
      TZ: ${TZ}
    depends_on:
      - sky-oap

  shardingproxy:
    image: apache/shardingsphere-proxy:5.3.2
    container_name: shardingsphere-proxy
    hostname: shardingsphere-proxy
    ports:
      - "3307:3307"
    volumes:
      - ../shardingproxy/conf:/opt/shardingsphere-proxy/conf
      - ../shardingproxy/ext-lib:/opt/shardingsphere-proxy/ext-lib
    environment:
      JVM_OPTS: "-Djava.awt.headless=true"
      LANG: ${LANG}
      TZ: ${TZ}
    command: server /data

  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # 设置集群名称
      cluster.name: elasticsearch
      # 以单一节点模式启动
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      LANG: ${LANG}
      TZ: ${TZ}
    volumes:
      - ../elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ../elk/elasticsearch/data:/usr/share/elasticsearch/data
      - ../elk/elasticsearch/logs:/usr/share/elasticsearch/logs

  kibana:
    image: kibana:7.17.6
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    volumes:
      - ../elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    environment:
      I18N_LOCALE: zh-CN
      # SERVER_PUBLICBASEURL: https://kibana.cloud.com  # 访问域名
      LANG: ${LANG}
      TZ: ${TZ}

  logstash:
    image: logstash:7.17.6
    container_name: logstash
    hostname: logstash
    ports:
      - "4560:4560"
    volumes:
      - ../elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ../elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    environment:
      LANG: ${LANG}
      TZ: ${TZ}
    depends_on:
      - elasticsearch

  zookeeper:
    image: 'bitnami/zookeeper:3.8.0'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_SERVER_ID: 1
      ZOO_PORT_NUMBER: 2181
      ZOO_ENABLE_ADMIN_SERVER: "no"       # 自带的控制台 一般用不上可自行开启
      ZOO_ADMIN_SERVER_PORT_NUMBER: 8080  # 自带控制台的端口
      LANG: ${LANG}
      TZ: ${TZ}

  kafka:
    image: 'bitnami/kafka:3.2.0'
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    volumes:
      - ../kafka/data:/bitnami/kafka/data
    environment:
      # 更多变量 查看文档 https://github.com/bitnami/bitnami-docker-kafka/blob/master/README.md
      KAFKA_BROKER_ID: 1
      # 监听端口
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      # 实际访问ip 本地用 127 内网用 192 外网用 外网ip
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://192.168.31.165:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: 127.0.0.1:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      LANG: ${LANG}
      TZ: ${TZ}
    depends_on:
      - zookeeper

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "19092:19092"
    environment:
      ZK_HOSTS: 127.0.0.1:2181
      APPLICATION_SECRET: letmein
      KAFKA_MANAGER_USERNAME: ruoyi
      KAFKA_MANAGER_PASSWORD: ruoyi123
      KM_ARGS: -Dhttp.port=19092
      LANG: ${LANG}
      TZ: ${TZ}
    depends_on:
      - kafka

  mqnamesrv:
    image: apache/rocketmq:4.9.4
    container_name: mqnamesrv
    hostname: mqnamesrv
    ports:
      - "9876:9876"
    volumes:
      - ../rocketmq/namesrv/logs:/home/rocketmq/logs/rocketmqlogs
    environment:
      JAVA_OPT: -server -Xms512m -Xmx512m
      LANG: ${LANG}
      TZ: ${TZ}
    command: sh mqnamesrv

  mqbroker1:
    image: apache/rocketmq:4.9.4
    container_name: mqbroker1
    hostname: mqbroker1
    ports:
      - "10911:10911"
      - "10909:10909"
      - "10912:10912"
    volumes:
      - ../rocketmq/broker1/conf/broker.conf:/home/rocketmq/rocketmq-4.9.4/conf/broker.conf
      - ../rocketmq/broker1/logs:/home/rocketmq/logs/rocketmqlogs
      - ../rocketmq/broker1/store:/home/rocketmq/store
    environment:
      JAVA_OPT_EXT: -server -Xms512M -Xmx512M -Xmn256m
      LANG: ${LANG}
      TZ: ${TZ}
    command: sh mqbroker -c /home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    depends_on:
      - mqnamesrv

  rocketmq-console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console
    hostname: rocketmq-console
    ports:
      - "19876:19876"
    environment:
      JAVA_OPTS: -Dserver.port=19876 -Drocketmq.namesrv.addr=127.0.0.1:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
      LANG: ${LANG}
      TZ: ${TZ}
    depends_on:
      - mqnamesrv

  rabbitmq:
    image: rabbitmq:3.10.6
    container_name: rabbitmq
    hostname: rabbitmq
    build:
      context: ./rabbitmq
    ports:
      - "15672:15672" # 管理界面端口
      - "5672:5672"   # api 端口
    volumes:
      - ../rabbitmq/log:/var/log/rabbitmq
      - ../rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ruoyi
      RABBITMQ_DEFAULT_PASS: ruoyi123
      LANG: ${LANG}
      TZ: ${TZ}

  prometheus:
    image: prom/prometheus:v2.40.1
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      LANG: ${LANG}
      TZ: ${TZ}

  grafana:
    image: grafana/grafana:9.2.4
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    volumes:
      - ../grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../grafana:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: ""                # 服务地址 用于指定外网ip或域名
      GF_SECURITY_ADMIN_PASSWORD: 123456    # admin 管理员密码
      LANG: ${LANG}
      TZ: ${TZ}


